version: 2.1
jobs:
  test_and_build:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - test_and_build